name: Crawler Link Checker Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_KEY }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Crawler Link Checker
      run: |
          docker build -t crawler-link-checker .
          docker tag crawler-link-checker:latest DOCKER_LOGIN/crawler-link-checker:latest
          docker push DOCKER_LOGIN/crawler-link-checker:latest
